# -*- coding: utf-8 -*-
"""Project4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12o0IgrgnAvQEVgn1I1hzWVy8znZ7PP4p

# NOTE: Please make a copy of this notebook before you start changing anything.

## Loading Data

We will fetch the first two chapters of Jane Austen's Pride and Prejudice from [Project Gutenberg](https://www.gutenberg.org/ebooks/1342)

### Function to fetch data
"""

def fetch_text(raw_url):
  """
  Fetches text content from a given URL, with caching.

  This function attempts to retrieve text data from the provided URL. To improve
  efficiency, it first checks a local cache directory ('cs_110_content/text_cache').
  If the content is found in the cache, it's read from there. Otherwise, it sends a
  GET request to the URL, saves the response text to the cache, and then returns it.
  Error handling is included for network issues or failed requests.

  Parameters:
  raw_url (str): The URL from which to fetch the text content.

  Returns:
  str: The fetched text content if successful, or an empty string if an error occurs.

  Example:
  >>> url = "https://www.gutenberg.org/cache/epub/1342/pg1342.txt"
  >>> text = fetch_text(url)
  >>> len(text) > 0
  True
  """
  import requests
  from pathlib import Path
  import hashlib

  CACHE_DIR = Path("cs_110_content/text_cache")
  CACHE_DIR.mkdir(parents=True, exist_ok=True)

  def _url_to_filename(url):
    url_hash = hashlib.sha1(url.encode("utf-8")).hexdigest()[:12]
    return CACHE_DIR / f"{url_hash}.txt"

  cache_path = _url_to_filename(raw_url)

  SUCCESS_MSG = "✅ Text fetched."
  FAILURE_MSG = "❌ Failed to fetch text."
  try:
    if not cache_path.exists():
      response = requests.get(raw_url, timeout=10)
      response.raise_for_status()
      text_data = response.text
      cache_path.write_text(text_data, encoding="utf-8")
    print(SUCCESS_MSG)
    return cache_path.read_text(encoding="utf-8")

  except Exception as e:
    print(FAILURE_MSG)
    print(f"Error: {e}")
    return ""

"""### Save the text in a variable"""

PRIDE_PREJUDICE_URL = "https://www.gutenberg.org/cache/epub/1342/pg1342.txt"

pride_prejudice_text = fetch_text(PRIDE_PREJUDICE_URL)

"""## Statistics about the data"""

def print_text_stats(text):
  """
  Calculates and prints statistics about a given text.

  This function takes a string of text and calculates the total number of characters,
  lines, and words. It then prints these statistics to the console.

  Parameters:
  text (str): The input text to analyze.

  Returns:
  None

  Example:
  >>> sample_text = "Hello world.\nThis is a test."
  >>> print_text_stats(sample_text)
  Number of characters: 29
  Number of lines: 2
  Number of words: 6
  """
  num_chars = len(text)

  lines = text.splitlines()
  num_lines = len(lines)

  num_words = 0
  for line in lines:
    words_in_line = line.split()
    num_words_in_line = len(words_in_line)
    num_words += num_words_in_line

  print(f"Number of characters: {num_chars}")
  print(f"Number of lines: {num_lines}")
  print(f"Number of words: {num_words}")

print_text_stats(pride_prejudice_text)

def get_word_counts(text):
  """
  Calculates the frequency of each word in a given text.

  This function processes a string of text, splits it into lines, and then further
  splits each line into individual words. It converts all words to lowercase and
  counts the occurrences of each unique word, storing them in a dictionary.

  Parameters:
  text (str): The input text to analyze.

  Returns:
  dict: A dictionary where keys are lowercase words and values are their counts.

  Example:
  >>> sample_text = "Hello world.\nHello there."
  >>> get_word_counts(sample_text)
  {'hello': 2, 'world.': 1, 'there.': 1}
  """
  word_counts = {}
  lines = text.splitlines()
  for line in lines:
    words = line.split()
    for word in words:
      word = word.lower()
      if word in word_counts:
        word_counts[word] += 1
      else:
        word_counts[word] = 1
  return word_counts

word_counts = get_word_counts(pride_prejudice_text)
print(word_counts)

"""# Lab Exercise

Do the following:
* Make a new Code Cell below and use Gemini to create a new function called `print_top_10_frequent_words` that will call the above get_word_counts() and print only the top 10 frequent words.
* Make a new Text Cell after that and write a one-two sentence summary of the code. <br>**HINT:** Use Gemini's "Explain Code" and prompt it to give you a good summary.
* Once you are done, download this notebook by clicking on the File Menu (below the name of the file), Download > Download .ipynb and submit it.
"""

# prompt: Make a new Code Cell below and use Gemini to create a new function called print_top_10_frequent_words that will call the above get_word_counts() and print only the top 10 frequent words.

import operator

def print_top_10_frequent_words(text):
    """
    Calculates and prints the top 10 most frequent words in a given text.

    This function utilizes `get_word_counts` to obtain word frequencies
    and then sorts them to identify and display the ten most common words.

    Parameters:
    text (str): The input text to analyze.

    Returns:
    None: Prints the top 10 words and their counts directly to the console.

    Example:
    >>> sample_text = "apple banana apple orange banana apple"
    >>> print_top_10_frequent_words(sample_text)
    # Expected output (order might vary slightly for ties, but counts are accurate):
    # apple: 3
    # banana: 2
    # orange: 1
    """
    word_counts = get_word_counts(text)
    sorted_word_counts = dict(sorted(word_counts.items(), key=operator.itemgetter(1), reverse=True))
    top_10_words = list(sorted_word_counts.items())[:10]  # Get the top 10 words and counts
    for word, count in top_10_words:
        print(f"{word}: {count}")

print_top_10_frequent_words(pride_prejudice_text)

#!pip install spacy

import spacy

nlp = spacy.load('en_core_web_sm')

def word_tokenization_normalization(text):
    """
    Performs tokenization and normalization on the input text.

    This function converts the input text to lowercase, processes it using spaCy,
    and then filters out stopwords, punctuation, numbers, and words with less
    than 3 characters. It lemmatizes the remaining words.

    Parameters:
    text (str): The input text to be processed.

    Returns:
    list: A list of normalized and lemmatized words.

    Example:
    >>> sample_text = "This is a sample sentence, with numbers 123 and stopwords."
    >>> nlp = spacy.load('en_core_web_sm') # Assuming nlp is loaded
    >>> word_tokenization_normalization(sample_text)
    ['sample', 'sentence', 'number']
    """
    text = text.lower() # lowercase
    doc = nlp(text)     # loading text into model

    words_normalized = []
    for word in doc:
        if word.text != '\n' \
        and not word.is_stop \
        and not word.is_punct \
        and not word.like_num \
        and len(word.text.strip()) > 2:
            word_lemmatized = str(word.lemma_)
            words_normalized.append(word_lemmatized)

    return words_normalized

doc_tokenized = word_tokenization_normalization(pride_prejudice_text)

print(doc_tokenized)

# prompt: write a function that takes in a list of words and returns a word count dictionary

def word_count(word_list):
    """
    Calculates the frequency of each word in a given list of words.

    This function takes a list of words, converts each word to lowercase,
    and counts the occurrences of each unique word, storing them in a dictionary.

    Parameters:
    word_list (list): A list of strings (words) to analyze.

    Returns:
    dict: A dictionary where keys are lowercase words and values are their counts.

    Example:
    >>> sample_list = ["Hello", "world", "Hello", "there"]
    >>> word_count(sample_list)
    {'hello': 2, 'world': 1, 'there': 1}
    """
    word_counts = {}
    for word in word_list:
      word = word.lower()
      if word in word_counts:
        word_counts[word] += 1
      else:
        word_counts[word] = 1
    return word_counts

new_counts = word_count(doc_tokenized)
print(new_counts)

# prompt: write a function that takes in a word count dictionary and prints the top 15 words with the most counts

import operator

def print_top_15_frequent_words(word_counts):
    """
    Prints the top 15 most frequent words from a word count dictionary.

    This function takes a dictionary of word counts, sorts it by count in descending
    order, and then prints the top 15 words along with their counts.

    Parameters:
    word_counts (dict): A dictionary where keys are words and values are their counts.

    Returns:
    None: Prints the top 15 words and their counts directly to the console.

    Example:
    >>> sample_word_counts = {'apple': 5, 'banana': 3, 'orange': 2, 'grape': 1, 'kiwi': 4}
    >>> print_top_15_frequent_words(sample_word_counts)
    # Expected output:
    # apple: 5
    # kiwi: 4
    # banana: 3
    # orange: 2
    # grape: 1
    """
    sorted_word_counts = dict(sorted(word_counts.items(), key=operator.itemgetter(1), reverse=True))
    top_15_words = list(sorted_word_counts.items())[:15]  # Get the top 15 words and counts
    for word, count in top_15_words:
        print(f"{word}: {count}")

print_top_15_frequent_words(new_counts)

"""1. The top 10 most frequent words from the basic get_word_counts() were all stop words, which include basic words like the, of, all, etc. These words don't tell you much about what the text could be about. While the top 15 words after using spaCy were all useful and descriptive words. These words give us hints about what the text is about or who the main characters are.
2. The results differ because using spaCy allowed us to use functions on the text to filter out stop words, punctuation, etc. Using spaCy's library made filtering this text super-fast and simple, which is seen in the function word_tokenization_normalization().
3. Removing the common words allows us to predict the main characters or what the text could be about. Based on the top 15 words, I can predict that it's about a family, maybe set in the past, and the main characters are Elizabeth and Darcy.

"""